apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: dinner
  namespace: default
spec:
  interval: 5m
  chart:
    spec:
      chart: 12factor
      sourceRef:
        kind: HelmRepository
        name: lalyos
        namespace: default
      interval: 1m
  values:
    title: Have a nice weekend, for real
    color: hotpink
    body: '<iframe src="https://giphy.com/embed/8CKb7LQZM9ypMoW8iJ" width="270" height="480" frameBorder="0" class="giphy-embed" allowFullScreen></iframe><p><a href="https://giphy.com/gifs/storyful-beer-oktoberfest-drinkign-8CKb7LQZM9ypMoW8iJ">via GIPHY</a></p>'
