apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: flux-demo
  namespace: default
spec:
  interval: 1m
  url: https://github.com/lalyos/flux-12factor-demo
  ref:
    branch: main
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: weekend
  namespace: default
spec:
  interval: 1m
  targetNamespace: default
  sourceRef:
    kind: GitRepository
    name: flux-demo
  path: "./"
  prune: true
  timeout: 1m